### ISSUE TITLE
Crash on Windows 10

### ISSUE THREAD

**Issue by buzmeg** [vulkano-rs/vulkano#1009]
Pulled current stable Rust and attempted to do "cargo run --bin triangle".

A window pops up with a blue background and a red triangle and then promptly crashes.  I did "set RUST_BACKTRACE=1" and got the attached backtrace.

Thanks.

```
>cargo run --bin triangle
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `c:\Users\andrewl\Desktop\vulkano\target\debug\triangle.exe`
Using device: Intel(R) UHD Graphics 620 (type: IntegratedGpu)
thread 'main' panicked at 'assertion failed: {
    let dur = Some(Duration::new(0, 0));
    self.fence.as_ref().map(|f| f.wait(dur).is_ok()).unwrap_or(true)
}', vulkano\src\swapchain\swapchain.rs:867:13
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:511
   6: std::panicking::begin_panic<str*>
             at C:\projects\rust\src\libstd\panicking.rs:445
   7: vulkano::swapchain::swapchain::{{impl}}::drop<winit::Window>
             at \<panic macros>:3
   8: core::ptr::drop_in_place<vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>
             at C:\projects\rust\src\libcore\ptr.rs:59
   9: core::ptr::drop_in_place<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>>
             at C:\projects\rust\src\libcore\ptr.rs:59
  10: core::ptr::drop_in_place<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>>
             at C:\projects\rust\src\libcore\ptr.rs:59
  11: core::ptr::drop_in_place<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>
             at C:\projects\rust\src\libcore\ptr.rs:59
  12: core::ptr::drop_in_place<vulkano::sync::future::fence_signal::FenceSignalFutureState<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>>
             at C:\projects\rust\src\libcore\ptr.rs:59
  13: vulkano::sync::future::fence_signal::FenceSignalFuture<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>::cleanup_finished_impl<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>
             at c:\Users\andrewl\Desktop\vulkano\vulkano\src\sync\future\fence_signal.rs:190
  14: vulkano::sync::future::fence_signal::{{impl}}::cleanup_finished<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>
             at c:\Users\andrewl\Desktop\vulkano\vulkano\src\sync\future\fence_signal.rs:318
  15: vulkano::sync::future::{{impl}}::cleanup_finished<GpuFuture>
             at c:\Users\andrewl\Desktop\vulkano\vulkano\src\sync\future\mod.rs:265
  16: vulkano::sync::future::join::{{impl}}::cleanup_finished<alloc::boxed::Box<GpuFuture>,vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>
             at c:\Users\andrewl\Desktop\vulkano\vulkano\src\sync\future\join.rs:73
  17: vulkano::command_buffer::traits::{{impl}}::cleanup_finished<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>,vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>
             at c:\Users\andrewl\Desktop\vulkano\vulkano\src\command_buffer\traits.rs:208
  18: vulkano::swapchain::swapchain::{{impl}}::cleanup_finished<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>,winit::Window>
             at c:\Users\andrewl\Desktop\vulkano\vulkano\src\swapchain\swapchain.rs:990
  19: vulkano::sync::future::fence_signal::FenceSignalFuture<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>::cleanup_finished_impl<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>
             at c:\Users\andrewl\Desktop\vulkano\vulkano\src\sync\future\fence_signal.rs:172
  20: vulkano::sync::future::fence_signal::{{impl}}::cleanup_finished<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>
             at c:\Users\andrewl\Desktop\vulkano\vulkano\src\sync\future\fence_signal.rs:318
  21: vulkano::sync::future::{{impl}}::cleanup_finished<GpuFuture>
             at c:\Users\andrewl\Desktop\vulkano\vulkano\src\sync\future\mod.rs:265
  22: triangle::main
             at .\src\bin\triangle.rs:338
  23: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  24: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  25: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:310
  26: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  27: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  28: std::panic::catch_unwind
             at C:\projects\rust\src\libstd\panic.rs:392
  29: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:58
  30: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  31: main
  32: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  33: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  34: BaseThreadInitThunk
  35: RtlUserThreadStart
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', libcore\result.rs:945:5
stack backtrace:
   0:     0x7ff67881e8a5 - std::sys::windows::backtrace::unwind_backtrace
                               at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1:     0x7ff678826bbe - std::sys_common::backtrace::_print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2:     0x7ff678826bbe - std::sys_common::backtrace::print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3:     0x7ff678817488 - std::panicking::default_hook::{{closure}}
                               at C:\projects\rust\src\libstd\panicking.rs:211
   4:     0x7ff678817141 - std::panicking::default_hook
                               at C:\projects\rust\src\libstd\panicking.rs:227
   5:     0x7ff678817cac - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:511
   6:     0x7ff678817a23 - std::panicking::continue_panic_fmt
                               at C:\projects\rust\src\libstd\panicking.rs:426
   7:     0x7ff6788176f8 - std::panicking::rust_begin_panic
                               at C:\projects\rust\src\libstd\panicking.rs:337
   8:     0x7ff67882b98b - core::panicking::panic_fmt
                               at C:\projects\rust\src\libcore\panicking.rs:92
   9:     0x7ff6785d0a52 - core::result::unwrap_failed<std::sys_common::poison::PoisonError<std::sync::mutex::MutexGuard<vulkano::sync::future::fence_signal::FenceSignalFutureState<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>>>>
                               at C:\projects\rust\src\libcore\macros.rs:26
  10:     0x7ff6785cbe73 - core::result::Result<std::sync::mutex::MutexGuard<vulkano::sync::future::fence_signal::FenceSignalFutureState<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>>, std::sys_common::poison::PoisonError<std::sync::mutex::MutexGuard<vulkano::sync::future::fence_signal::FenceSignalFutureState<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>>>>::unwrap<std::sync::mutex::MutexGuard<vulkano::sync::future::fence_signal::FenceSignalFutureState<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>>,std::sys_common::poison::PoisonError<std::sync::mutex::MutexGuard<vulkano::sync::future::fence_signal::FenceSignalFutureState<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>>>>
                               at C:\projects\rust\src\libcore\result.rs:782
  11:     0x7ff67866b914 - vulkano::sync::future::fence_signal::{{impl}}::drop<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>
                               at c:\Users\andrewl\Desktop\vulkano\vulkano\src\sync\future\fence_signal.rs:428
  12:     0x7ff678624dde - core::ptr::drop_in_place<vulkano::sync::future::fence_signal::FenceSignalFuture<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  13:     0x7ff678625850 - core::ptr::drop_in_place<alloc::boxed::Box<GpuFuture>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  14:     0x7ff67863766a - triangle::main
                               at c:\Users\andrewl\Desktop\vulkano\examples\src\bin\triangle.rs:486
  15:     0x7ff86d5ac32f - _C_specific_handler
  16:     0x7ff86d5a297d - _TypeMatch
  17:     0x7ff86d5a1c97 - is_exception_typeof
  18:     0x7ff86d5aba81 - _CxxFrameHandler3
  19:     0x7ff874e5ed6c - _chkstk
  20:     0x7ff874dc766f - RtlUnwindEx
  21:     0x7ff86d5abe00 - FindAndUnlinkFrame
  22:     0x7ff86d5a2ac8 - _TypeMatch
  23:     0x7ff86d5a2208 - is_exception_typeof
  24:     0x7ff86d5a1e3f - is_exception_typeof
  25:     0x7ff86d5aba81 - _CxxFrameHandler3
  26:     0x7ff874e5ecec - _chkstk
  27:     0x7ff874dc6c85 - RtlWalkFrameChain
  28:     0x7ff874dc52c9 - RtlRaiseException
  29:     0x7ff871b3a387 - RaiseException
  30:     0x7ff86d5a43dc - CxxThrowException
  31:     0x7ff67882a897 - panic_unwind::imp::panic
                               at C:\projects\rust\src\libpanic_unwind\seh.rs:291
  32:     0x7ff67882a897 - panic_unwind::__rust_start_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:121
  33:     0x7ff678817d87 - std::panicking::rust_panic
                               at C:\projects\rust\src\libstd\panicking.rs:559
  34:     0x7ff678817d67 - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:531
  35:     0x7ff6786f9902 - std::panicking::begin_panic<str*>
                               at C:\projects\rust\src\libstd\panicking.rs:445
  36:     0x7ff67863ebae - vulkano::swapchain::swapchain::{{impl}}::drop<winit::Window>
                               at \<panic macros>:3
  37:     0x7ff678624bbe - core::ptr::drop_in_place<vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  38:     0x7ff678625480 - core::ptr::drop_in_place<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  39:     0x7ff678620fe8 - core::ptr::drop_in_place<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  40:     0x7ff67862076a - core::ptr::drop_in_place<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  41:     0x7ff67862446d - core::ptr::drop_in_place<vulkano::sync::future::fence_signal::FenceSignalFutureState<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  42:     0x7ff67866eaf4 - vulkano::sync::future::fence_signal::FenceSignalFuture<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>::cleanup_finished_impl<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>
                               at c:\Users\andrewl\Desktop\vulkano\vulkano\src\sync\future\fence_signal.rs:190
  43:     0x7ff67866c112 - vulkano::sync::future::fence_signal::{{impl}}::cleanup_finished<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>
                               at c:\Users\andrewl\Desktop\vulkano\vulkano\src\sync\future\fence_signal.rs:318
  44:     0x7ff678689fe4 - vulkano::sync::future::{{impl}}::cleanup_finished<GpuFuture>
                               at c:\Users\andrewl\Desktop\vulkano\vulkano\src\sync\future\mod.rs:265
  45:     0x7ff6785e2252 - vulkano::sync::future::join::{{impl}}::cleanup_finished<alloc::boxed::Box<GpuFuture>,vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>
                               at c:\Users\andrewl\Desktop\vulkano\vulkano\src\sync\future\join.rs:73
  46:     0x7ff678653e62 - vulkano::command_buffer::traits::{{impl}}::cleanup_finished<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>,vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>
                               at c:\Users\andrewl\Desktop\vulkano\vulkano\src\command_buffer\traits.rs:208
  47:     0x7ff67863fda2 - vulkano::swapchain::swapchain::{{impl}}::cleanup_finished<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>,winit::Window>
                               at c:\Users\andrewl\Desktop\vulkano\vulkano\src\swapchain\swapchain.rs:990
  48:     0x7ff67866eaa5 - vulkano::sync::future::fence_signal::FenceSignalFuture<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>::cleanup_finished_impl<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>
                               at c:\Users\andrewl\Desktop\vulkano\vulkano\src\sync\future\fence_signal.rs:172
  49:     0x7ff67866c112 - vulkano::sync::future::fence_signal::{{impl}}::cleanup_finished<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>
                               at c:\Users\andrewl\Desktop\vulkano\vulkano\src\sync\future\fence_signal.rs:318
  50:     0x7ff678689fe4 - vulkano::sync::future::{{impl}}::cleanup_finished<GpuFuture>
                               at c:\Users\andrewl\Desktop\vulkano\vulkano\src\sync\future\mod.rs:265
  51:     0x7ff678635bf0 - triangle::main
                               at c:\Users\andrewl\Desktop\vulkano\examples\src\bin\triangle.rs:338
  52:     0x7ff67868b1af - std::rt::lang_start::{{closure}}<()>
                               at C:\projects\rust\src\libstd\rt.rs:74
  53:     0x7ff678817656 - std::rt::lang_start_internal::{{closure}}
                               at C:\projects\rust\src\libstd\rt.rs:59
  54:     0x7ff678817656 - std::panicking::try::do_call<closure,i32>
                               at C:\projects\rust\src\libstd\panicking.rs:310
  55:     0x7ff67882a7b1 - panic_unwind::__rust_maybe_catch_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  56:     0x7ff67881c052 - std::panicking::try
                               at C:\projects\rust\src\libstd\panicking.rs:289
  57:     0x7ff67881c052 - std::panic::catch_unwind
                               at C:\projects\rust\src\libstd\panic.rs:392
  58:     0x7ff67881c052 - std::rt::lang_start_internal
                               at C:\projects\rust\src\libstd\rt.rs:58
  59:     0x7ff67868b187 - std::rt::lang_start<()>
                               at C:\projects\rust\src\libstd\rt.rs:74
  60:     0x7ff67863b372 - main
  61:     0x7ff67883771b - invoke_main
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  62:     0x7ff67883771b - __scrt_common_main_seh
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  63:     0x7ff874213033 - BaseThreadInitThunk
  64:     0x7ff874e31430 - RtlUserThreadStart
thread panicked while panicking. aborting.
error: process didn't exit successfully: `c:\Users\andrewl\Desktop\vulkano\target\debug\triangle.exe` (exit code: 3221225501)

```

**Comment by rukai** [comment]
This is a dupe of https://github.com/vulkano-rs/vulkano/issues/960
I do want to look into it but I've been a bit distracted... and wont have time for a while.

**Comment by JohnDoneth** [comment]
Do you know what your Vulkan driver version is? I had a lot of problems on Intel before they released their >1.0 drivers.

**Comment by buzmeg** [comment]
Intel UHD Graphics 620 Driver Version 24.20.100.6194 with date 6/20/2018

Vulkan version 1.1.77 as reported by vulkaninfo

Windows 10 on an LG Gram.  Side Note: I am driving a 4K monitor with my HDMI port in case that matters

**Comment by tyoc213** [comment]
Same problem Im having... it is fixed in either 

- build is as release
- mod the source to add 1 second for that fence... some like

```diff
diff --git a/vulkano/src/swapchain/swapchain.rs b/vulkano/src/swapchain/swapchain.rs
index e0e88530..8d3ed6a5 100644
--- a/vulkano/src/swapchain/swapchain.rs
+++ b/vulkano/src/swapchain/swapchain.rs
@@ -865,7 +865,7 @@ impl<W> Drop for SwapchainAcquireFuture<W> {
             // validation layers about using a fence whose state hasn't been checked (even though
             // we know for sure that it must've been signalled).
             debug_assert!({
-                              let dur = Some(Duration::new(0, 0));
+                              let dur = Some(Duration::from_millis(10));
                               self.fence
                                   .as_ref()
                                   .map(|f| f.wait(dur).is_ok())
```
This error happen more when for example watching a stream or video and try to run the examples... I guess more "fast" machines doesnt pass by this error.

**Comment by tyoc213** [comment]
I just make a branch that pass None instead of a duration of 0 which causes the eventual false for `debug_assert!`, if this would be the correct way, I can send the PR.

**Comment by rukai** [comment]
Sadly that is not the correct solution. As per the comment above the code you changed, the logic of vulkano is supposed to be that when the code reaches that line "we know for sure that it must've been signaled".

Somehow this invariant is not upheld and we need to figure out how/why in order to fix this issue.

**Comment by Nopey** [comment]
Its odd that the validation layers don't trust that the fence has been signalled.
Is it possible that the CPU needs to wait for a GPU fetch for the fence status, even though the fence has been signalled? Or have I misunderstood fences.

**Comment by rukai** [comment]
https://github.com/vulkano-rs/vulkano/issues/385 This is interesting, it explains the initial design of the futures system.

**Comment by buzmeg** [comment]
Closing.
