### ISSUE TITLE
OomError(OutOfHostMemory) When Creating Instance

### ISSUE THREAD

**Issue by AustinJ235** [vulkano-rs/vulkano#1178]
*   Version of vulkano: 3518268b7f8080f44c06daf33c90c5b8cb4986d4
*   OS: Void Linux with Linux 4.19
*   GPU (the selected PhysicalDevice): Nvidia GTX 780
*   GPU Driver: nvidia-418.43
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: triangle.rs

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OomError(OutOfHostMemory)', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/7c19e1eed5418b8c02be65d678417b241ee01a3e/src/libcore/macros.rs:16
   9: <core::result::Result<T, E>>::unwrap
             at /rustc/7c19e1eed5418b8c02be65d678417b241ee01a3e/src/libcore/result.rs:798
  10: triangle::main
             at examples/src/bin/triangle.rs:49
  11: std::rt::lang_start::{{closure}}
             at /rustc/7c19e1eed5418b8c02be65d678417b241ee01a3e/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/7c19e1eed5418b8c02be65d678417b241ee01a3e/src/libstd/rt.rs:64
  16: main
  17: __libc_start_main
             at ../csu/libc-start.c:308
  18: _start
             at ../sysdeps/x86_64/start.S:120
```

https://github.com/vulkano-rs/vulkano/blob/3518268b7f8080f44c06daf33c90c5b8cb4986d4/examples/src/bin/triangle.rs#L49

# Issue
System and gpu both have enough memory. I haven't investigated further at this time.

**Comment by AustinJ235** [comment]
This might be an issue with the graphics installation of my distro. If I manually set the `VK_ICD_FILENAMES` environment variable vulkan will correctly work.

**Comment by AustinJ235** [comment]
I'll just add an export to `/etc/profile.d/`.
