### ISSUE TITLE
compute shader example

### ISSUE THREAD

**Issue by simdimdim** [vulkano-rs/vulkano#1273]
*   Version of vulkano: 0.16+
*   OS: arch linux
*   GPU (the selected PhysicalDevice): gtx 960
*   GPU Driver: nvidia-beta

something between 0.14 and 0.16 breaks the compute shader example for me with 
> 'Device extension "khr_storage_buffer_storage_class" required'

with deps looking like this: 
```
winit="0.19"
vulkano={git="https://github.com/vulkano-rs/vulkano"}
vulkano-win={git="https://github.com/vulkano-rs/vulkano"}
vulkano-shaders={git="https://github.com/vulkano-rs/vulkano"}
vk-sys ={git = "https://github.com/vulkano-rs/vulkano"}
```
with 
```
winit="0.19"
vulkano="0.14"
vulkano-win="0.14"
vulkano-shaders="0.14"
vk-sys ="*" 
```
its fine

not quite sure if I'm doing something wrong, or its the example that's wrong, please light the way for me.

the full trace looks like this:
```
Device initialized
thread 'main' panicked at 'Device extension "khr_storage_buffer_storage_class" required', hatch/src/bin/shaders.rs:80:13
stack backtrace:
   0:     0x55b3de1bb674 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x55b3de1bb674 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x55b3de1bb674 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x55b3de1bb674 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x55b3de1d4d5c - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x55b3de1b9c37 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x55b3de1bda45 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x55b3de1bda45 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55b3de1bda45 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x55b3de1bd736 - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x55b3de1be0e5 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x55b3de1bdc82 - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                               at src/libstd/panicking.rs:380
  12:     0x55b3de1bdbdc - std::panicking::begin_panic_fmt::hecb5f06c798651bd
                               at src/libstd/panicking.rs:335
  13:     0x55b3de051777 - shaders::main::cs::Shader::load::h797f1c7981006610
                               at hatch/src/bin/shaders.rs:80
  14:     0x55b3de05090b - shaders::main::h7cd1cc6c17e1015c
                               at hatch/src/bin/shaders.rs:97
  15:     0x55b3de082c80 - std::rt::lang_start::{{closure}}::hcb1ccace66c4c6ee
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  16:     0x55b3de1bdb13 - std::rt::lang_start_internal::{{closure}}::ha04574f12d97cbe2
                               at src/libstd/rt.rs:49
  17:     0x55b3de1bdb13 - std::panicking::try::do_call::h7c2a8488f72db90c
                               at src/libstd/panicking.rs:292
  18:     0x55b3de1bfa6a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  19:     0x55b3de1be5dd - std::panicking::try::hc3a9b5da4250385d
                               at src/libstd/panicking.rs:271
  20:     0x55b3de1be5dd - std::panic::catch_unwind::hf27600bf8c37809a
                               at src/libstd/panic.rs:394
  21:     0x55b3de1be5dd - std::rt::lang_start_internal::h409d4f2fe51133b0
                               at src/libstd/rt.rs:48
  22:     0x55b3de082c59 - std::rt::lang_start::ha042339f2d90cfd8
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  23:     0x55b3de0528ca - main
  24:     0x7f0298796153 - __libc_start_main
  25:     0x55b3de04f15e - _start
  26:                0x0 - <unknown>

```

**Comment by simdimdim** [comment]
problem was resolved, after adding the required extension. and after a small mishap with the buffer being too big for my gpu I've hit another snag of the output not matching the expected...

**Comment by nickwilcox** [comment]
Fixed with https://github.com/vulkano-rs/vulkano/pull/1275 (also includes the change to require `khr_storage_buffer_storage_class`)
