### ISSUE TITLE
How to implement two or more sets?

### ISSUE THREAD

**Issue by AndrewS236** [vulkano-rs/vulkano#1340]
Version of vulkano: 0.18.0

The code is based off the `triangle.rs` example and `image/main.rs`.

I could not find any documents, forums, and issues referring to creating multiple sets. So I am asking here as a last resort to how to implement two or more sets in a `GraphicsPipeline` object? I keep getting panic each time when I try to use multiple sets. And for context, I am trying to create a 3D cube with perspective and sampled texture.

The current pipeline:

        let pipeline = Arc::new(GraphicsPipeline::start()
            .vertex_input_single_buffer::<Vertex>()
            .vertex_shader(vs.main_entry_point(), ())
            .triangle_fan()
            .viewports_dynamic_scissors_irrelevant(1)
            .fragment_shader(fs.main_entry_point(), ())
            .render_pass(Subpass::from(render_pass.clone(), 0).unwrap())
            .build(device.clone()).unwrap());

`set0` is for binding the texture to the fragment shader.
`set1` is for binding the Model, View, Projection matrix to the vertex shader.
The two sets I like to add:

        let layout0 = pipeline.descriptor_set_layout(0).unwrap();
        let set0 = Arc::new(PersistentDescriptorSet::start(layout0.clone())
            .add_sampled_image(texture.clone(), sampler.clone()).unwrap()
            .build().unwrap()
        );

        let layout1 = pipeline.descriptor_set_layout(1).unwrap();
        let set1 = Arc::new(PersistentDescriptorSet::start(layout1.clone())
            .add_buffer(sub_buf.clone()).unwrap()
            .build().unwrap()
        );

I do not know how you properly set multiple sets though I implemented through tuples:

        let command_buffer = AutoCommandBufferBuilder::primary_one_time_submit(device.clone(), queue.family()).unwrap()
            .begin_render_pass(framebuffer[image_num].clone(), false, vec![[0.0, 0.0, 1.0, 1.0].into()]).unwrap()
            .draw(pipeline.clone(), &dynamic_state, vertex_buffer.clone(), (set0.clone(), set1.clone()), ()).unwrap()
            .end_render_pass().unwrap()
            .build().unwrap();

Error:

        thread 'main' panicked at 'Can't be union-ed', C:\Users\Andrew Shen\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.18.0\src\descriptor\pipeline_layout\union.rs:61:40
        stack backtrace:
    
        // -- cut --
    
        12: core::option::expect_failed
        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\option.rs:1191
        13: core::option::Option<vulkano::descriptor::descriptor::DescriptorDesc>::expect<vulkano::descriptor::descriptor::DescriptorDesc>
        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\option.rs:347
        14: vulkano::descriptor::pipeline_layout::union::{{impl}}::descriptor<mineblock::vs::Layout,mineblock::fs::Layout>
        at C:\Users\Andrew Shen\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.18.0\src\descriptor\pipeline_layout\union.rs:61
        15: vulkano::descriptor::pipeline_layout::tweaks::{{impl}}::descriptor<vulkano::descriptor::pipeline_layout::union::PipelineLayoutDescUnion<mineblock::vs::Layout, mineblock::fs::Layout>>
        at C:\Users\Andrew Shen\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.18.0\src\descriptor\pipeline_layout\tweaks.rs:56
        16: vulkano::descriptor::pipeline_layout::limits_check::check_desc_against_limits<vulkano::descriptor::pipeline_layout::tweaks::PipelineLayoutDescTweaks<vulkano::descriptor::pipeline_layout::union::PipelineLayoutDescUnion<mineblock::vs::Layout, mineblock::fs:
        at C:\Users\Andrew Shen\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.18.0\src\descriptor\pipeline_layout\limits_check.rs:43
        17: vulkano::descriptor::pipeline_layout::traits::PipelineLayoutDesc::check_against_limits<vulkano::descriptor::pipeline_layout::tweaks::PipelineLayoutDescTweaks<vulkano::descriptor::pipeline_layout::union::PipelineLayoutDescUnion<mineblock::vs::Layout, mineb
        at C:\Users\Andrew Shen\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.18.0\src\descriptor\pipeline_layout\traits.rs:108
        18: vulkano::descriptor::pipeline_layout::sys::PipelineLayout<vulkano::descriptor::pipeline_layout::tweaks::PipelineLayoutDescTweaks<vulkano::descriptor::pipeline_layout::union::PipelineLayoutDescUnion<mineblock::vs::Layout, mineblock::fs::Layout>>>::new<vulk
        at C:\Users\Andrew Shen\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.18.0\src\descriptor\pipeline_layout\sys.rs:56
        19: vulkano::descriptor::pipeline_layout::traits::PipelineLayoutDesc::build<vulkano::descriptor::pipeline_layout::tweaks::PipelineLayoutDescTweaks<vulkano::descriptor::pipeline_layout::union::PipelineLayoutDescUnion<mineblock::vs::Layout, mineblock::fs::Layou
        at C:\Users\Andrew Shen\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.18.0\src\descriptor\pipeline_layout\traits.rs:118
        20: vulkano::pipeline::graphics_pipeline::builder::GraphicsPipelineBuilder<vulkano::pipeline::vertex::single::SingleBufferDefinition<mineblock::Vertex>, vulkano::pipeline::shader::GraphicsEntryPoint<(), mineblock::vs::MainInput, mineblock::vs::MainOutput, min
        at C:\Users\Andrew Shen\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.18.0\src\pipeline\graphics_pipeline\builder.rs:289
        21: vulkano::pipeline::graphics_pipeline::builder::GraphicsPipelineBuilder<vulkano::pipeline::vertex::single::SingleBufferDefinition<mineblock::Vertex>, vulkano::pipeline::shader::GraphicsEntryPoint<(), mineblock::vs::MainInput, mineblock::vs::MainOutput, min
        at C:\Users\Andrew Shen\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.18.0\src\pipeline\graphics_pipeline\builder.rs:162
        22: mineblock::main
        at .\src\main.rs:152
    
        // -- cut --
    
        Process finished with exit code 101

**Comment by AndrewS236** [comment]
Whoops! I should be putting my `pipeline` object in the main windows event loop with the rest of the sets.
