### ISSUE TITLE
Compute Shader read buffer segfault

### ISSUE THREAD

**Issue by dmyTRUEk** [vulkano-rs/vulkano#1478]
# System info:

* Version of Vulkano: `0.20.0`
* Version of Rust: `cargo 1.49.0 (d00d64df9 2020-12-05)`
* OS: Manjaro Linux, `uname -a`:
  `Linux myshko-pc-mnjr 5.10.7-3-MANJARO #1 SMP PREEMPT Fri Jan 15 21:11:34 UTC 2021 x86_64 GNU/Linux`
* GPU (the selected PhysicalDevice): Name: Radeon RX 580 Series (4 GB)
* GPU Driver: from `lshw -c video`: `driver=amdgpu`
* minimal complete `main.rs` file that demonstrates the issue: https://github.com/dmyTRUEk/vulkano-compute-shader-capacity-overflow

# Issue:
`thread 'main' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:542:5`
problem is after i "pass" buffers to gpu, their sizes unreasonable big (21474836484 and 4611686018427387904 elements), and i cant read information from them:
`println!("{:?}", content_in[0]);` or `println!("{:?}", content_out[0]);` results in:
`56473 segmentation fault (core dumped)  RUST_BACKTRACE=full cargo run`

`RUST_BACKTRACE=full cargo run` gives this:
```
    Finished dev [unoptimized + debuginfo] target(s) in 2.94s
     Running `target/debug/vk_proj_1_min_example_capacity_overflow`
Program Started!
Name: Radeon RX 580 Series
Found a queue family with 1 queue(s)
Found a queue family with 4 queue(s)
Found a queue family with 2 queue(s)
data_in_size = 6
in size: 21474836484
out size: 4611686018427387904
thread 'main' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:542:5
stack backtrace:
   0:     0x555973ef4260 - std::backtrace_rs::backtrace::libunwind::trace::h04d12fdcddff82aa
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:     0x555973ef4260 - std::backtrace_rs::backtrace::trace_unsynchronized::h1459b974b6fbe5e1
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x555973ef4260 - std::sys_common::backtrace::_print_fmt::h9b8396a669123d95
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x555973ef4260 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he009dcaaa75eed60
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x555973f122dc - core::fmt::write::h77b4746b0dea1dd3
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/fmt/mod.rs:1078:17
   5:     0x555973ef22d2 - std::io::Write::write_fmt::heb7e50902e98831c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/mod.rs:1518:15
   6:     0x555973ef65e5 - std::sys_common::backtrace::_print::h2d880c9e69a21be9
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x555973ef65e5 - std::sys_common::backtrace::print::h5f02b1bb49f36879
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x555973ef65e5 - std::panicking::default_hook::{{closure}}::h658e288a7a809b29
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:208:50
   9:     0x555973ef6288 - std::panicking::default_hook::hb52d73f0da9a4bb8
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:227:9
  10:     0x555973ef6d81 - std::panicking::rust_panic_with_hook::hfe7e1c684e3e6462
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:593:17
  11:     0x555973ef6897 - std::panicking::begin_panic_handler::{{closure}}::h42939e004b32765c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:497:13
  12:     0x555973ef471c - std::sys_common::backtrace::__rust_end_short_backtrace::h9d2070f7bf9fd56c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x555973ef6829 - rust_begin_unwind
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
  14:     0x555973f10c41 - core::panicking::panic_fmt::ha0bb065d9a260792
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
  15:     0x555973f10b8d - core::panicking::panic::h339b30ca166fd852
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:50:5
  16:     0x555973f0c49a - alloc::raw_vec::capacity_overflow::h49c6e21bc9da0bad
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/raw_vec.rs:542:5
  17:     0x555973dedbf0 - alloc::raw_vec::RawVec<T,A>::allocate_in::h127f3bcd0d58b6d0
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/raw_vec.rs:182:27
  18:     0x555973df323c - alloc::raw_vec::RawVec<T,A>::with_capacity_in::h0ad8aa6964468d5a
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/raw_vec.rs:130:9
  19:     0x555973ded65e - alloc::raw_vec::RawVec<T>::with_capacity::h08738113fc6c37b8
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/raw_vec.rs:93:9
  20:     0x555973da0aee - alloc::vec::Vec<T>::with_capacity::h8338a2904f2091bf
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/vec.rs:363:20
  21:     0x555973df62c3 - alloc::slice::hack::to_vec::ha522a44eef4e5bfd
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/slice.rs:159:23
  22:     0x555973e01a1a - alloc::slice::<impl [T]>::to_vec::h694a4bc832047454
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/slice.rs:395:9
  23:     0x555973da29ba - <alloc::vec::Vec<T> as core::clone::Clone>::clone::hce29a0c95ff93e18
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/vec.rs:1904:9
  24:     0x555973e0bda6 - vk_proj_1_min_example_capacity_overflow::make_calculations_on_gpu::h5772a105b28f28a9
                               at /home/myshko/Code/rust/Vulkan/vk_proj_1_min_example_capacity_overflow/src/main.rs:134:12
  25:     0x555973e0d096 - vk_proj_1_min_example_capacity_overflow::main::h5e8aee9439547f2d
                               at /home/myshko/Code/rust/Vulkan/vk_proj_1_min_example_capacity_overflow/src/main.rs:204:15
  26:     0x555973de213b - core::ops::function::FnOnce::call_once::ha45f0317636bd602
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:227:5
  27:     0x555973dded2e - std::sys_common::backtrace::__rust_begin_short_backtrace::h6bbc161fb0f261af
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:125:18
  28:     0x555973e18d71 - std::rt::lang_start::{{closure}}::h973e3e89e5e7955f
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/rt.rs:66:18
  29:     0x555973ef71a7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h57e2a071d427b24c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:259:13
  30:     0x555973ef71a7 - std::panicking::try::do_call::h81cbbe0c3b30a28e
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:381:40
  31:     0x555973ef71a7 - std::panicking::try::hbeeb95b4e1f0a876
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:345:19
  32:     0x555973ef71a7 - std::panic::catch_unwind::h59c48ccb40a0bf20
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panic.rs:396:14
  33:     0x555973ef71a7 - std::rt::lang_start_internal::ha53ab63f88fee728
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/rt.rs:51:25
  34:     0x555973e18d47 - std::rt::lang_start::h56dcea1fff9978fe
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/rt.rs:65:5
  35:     0x555973e0d2da - main
  36:     0x7f524261e152 - __libc_start_main
  37:     0x555973d7c09e - _start
  38:                0x0 - <unknown>
```

For me, this problem is similar to #1466, #1037, #1087, #985
I tried what was there, but it had no effect.

Maybe its just my code problem, if so, please correct me.

PS: I'm not a programer, just physicist, so please be more explanatory to me :)

**Comment by stephan-cr** [comment]
@dmyTRUEk I wouldn't say it's your code, it's the interface, which is hard to use. :-(

If, instead of

```rust
let data_buffer_in = CpuAccessibleBuffer::from_data(
        device.clone(),
        BufferUsage::all(),
        false,
        data_in,
    ).expect("failed to create buffer");
```

you write

```rust
    let data_buffer_in = CpuAccessibleBuffer::from_iter(
        device.clone(),
        BufferUsage::all(),
        false,
        data_in.into_iter(),
    ).expect("failed to create buffer");
```

it should work. `CpuAccessibleBuffer::from_data<T>(...)` seems to assume, that the type `T` is a flat memory structure (like a primitive array for example), which isn't true for `Vec`.

**Comment by dmyTRUEk** [comment]
Thanks a lot, it works!

So, maybe it is possible to add some warning in `CpuAccessibleBuffer::from_data` when non flat memory structure passed?
