### ISSUE TITLE
Selecting which GPU to run on?

### ISSUE THREAD

**Issue by Keyframe** [vulkano-rs/vulkano#1611]
*   Version of vulkano: 629fff826ea5f2cef3867e83ee84e99ef91a6680 - master, Mon Jun 14 2021
*   OS: Pop_OS! 20.10
*   GPU (the selected PhysicalDevice): 3090 RTX, GTX 1650, intel integrated
*   GPU Driver: 460.27.04, CUDA 11.2

# Issue

I've tried to run the `cargo test --all` and then `cargo run --bin triangle`, but the thing runs on intel integrated graphics. Is there a way for it to (pre) select running on a desired graphics card, like in my case I'd rather run it on 3090 RTX? It's an external GPU enclosure, not that it should matter..

**Comment by Keyframe** [comment]
What I did since is to run it with:

`RUST_BACKTRACE=full VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json cargo run --bin triangle`

I got back this:

```
Using device: GeForce RTX 3090 (type: DiscreteGpu)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FeatureRestrictionNotMet(FeatureRestrictionError { feature: "attachment_fragment_shading_rate", restriction: ConflictsFeature("shading_rate_image") })', examples/src/bin/triangle.rs:139:6
stack backtrace:
   0:     0x55f365a227e0 - std::backtrace_rs::backtrace::libunwind::trace::hfa838fc631229987
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55f365a227e0 - std::backtrace_rs::backtrace::trace_unsynchronized::h93a23e36ec026219
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f365a227e0 - std::sys_common::backtrace::_print_fmt::hba56c7f796a4152f
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55f365a227e0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h214637f1e26310e1
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55f365a4465c - core::fmt::write::h7aa6cd0067dca82a
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/core/src/fmt/mod.rs:1110:17
   5:     0x55f365a1fc15 - std::io::Write::write_fmt::heb07fc0616bbd06d
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/io/mod.rs:1588:15
   6:     0x55f365a2484b - std::sys_common::backtrace::_print::h2c2441c37e894fb5
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55f365a2484b - std::sys_common::backtrace::print::h4fb679ac439362ea
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55f365a2484b - std::panicking::default_hook::{{closure}}::h56bbadec2356e5d2
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/panicking.rs:208:50
   9:     0x55f365a24321 - std::panicking::default_hook::hb25822b45f6fdc4e
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/panicking.rs:225:9
  10:     0x55f365a24f14 - std::panicking::rust_panic_with_hook::h4da5578e7277d2d4
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/panicking.rs:622:17
  11:     0x55f365a249f7 - std::panicking::begin_panic_handler::{{closure}}::h003783ddb3cba4e8
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/panicking.rs:519:13
  12:     0x55f365a22cbc - std::sys_common::backtrace::__rust_end_short_backtrace::hd138d2032731ed21
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55f365a24959 - rust_begin_unwind
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/panicking.rs:515:5
  14:     0x55f36521a271 - core::panicking::panic_fmt::hbe99dddd3092ba3c
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/core/src/panicking.rs:92:14
  15:     0x55f36521a363 - core::result::unwrap_failed::hf79563fef9d11ab8
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/core/src/result.rs:1355:5
  16:     0x55f36527440d - core::result::Result<T,E>::unwrap::hdf98bbabed99534e
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/core/src/result.rs:1037:23
  17:     0x55f3652c5e9a - triangle::main::h678bd93d9e43c1d6
                               at /home/dominik/pr/rust/vulkano/examples/src/bin/triangle.rs:133:32
  18:     0x55f36529cdcb - core::ops::function::FnOnce::call_once::h9d6013e4ca436c6d
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/core/src/ops/function.rs:227:5
  19:     0x55f36523ab3e - std::sys_common::backtrace::__rust_begin_short_backtrace::h765ae75206756cd9
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/sys_common/backtrace.rs:125:18
  20:     0x55f365262031 - std::rt::lang_start::{{closure}}::hf8e1df9153d3f363
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/rt.rs:49:18
  21:     0x55f365a25419 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd933294140eb11aa
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/core/src/ops/function.rs:259:13
  22:     0x55f365a25419 - std::panicking::try::do_call::h8342fe3d9218b807
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/panicking.rs:401:40
  23:     0x55f365a25419 - std::panicking::try::hcbd73d6d0d58a8f0
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/panicking.rs:365:19
  24:     0x55f365a25419 - std::panic::catch_unwind::hde9cf73f810acfcc
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/panic.rs:434:14
  25:     0x55f365a25419 - std::rt::lang_start_internal::heb39e7ea6e5d6f6f
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/rt.rs:34:21
  26:     0x55f365262010 - std::rt::lang_start::hecb60b27005d22b8
                               at /rustc/a85f584aebd9b08314bf30b9adc17b4a752143e5/library/std/src/rt.rs:48:5
  27:     0x55f3652c898c - main
  28:     0x7feafd47acb2 - __libc_start_main
  29:     0x55f36521aa6e - _start
  30:                0x0 - <unknown>
```

**Comment by AustinJ235** [comment]
If you wish to use other devices than the first one you'd need to modify this line for example:
https://github.com/vulkano-rs/vulkano/blob/629fff826ea5f2cef3867e83ee84e99ef91a6680/examples/src/bin/triangle.rs#L68

You can use `PhysicalDevice::properties()` and that [struct](https://basalt.dev/docs/vulkano/vulkano/device/struct.Properties.html) will have the fields `device_name`, `device_type` that'll interest you.

**Comment by Rua** [comment]
The panic error you got is because the examples try to enable every feature, even though that's not actually allowed because some features conflict with others. That's a bug in Vulkano's examples that needs to be fixed.

**Comment by Keyframe** [comment]
I was worried 3090 was already obsolete!

**Comment by Keyframe** [comment]
@Rua I can confirm your PR works:
![image](https://user-images.githubusercontent.com/321193/122951938-f2a1e100-d37d-11eb-96ed-e3170dab0f67.png)
