### ISSUE TITLE
Empty `PersistentDescriptorSet`s sometimes panic upon creation

### ISSUE THREAD

**Issue by Tenebryo** [vulkano-rs/vulkano#1632]
*   Version of vulkano: 0.24.0
*   OS: Windows
*   GPU (the selected PhysicalDevice): RTX 2070 Super
*   GPU Driver: 466.63

# Issue

A shader I was writing had multiple descriptor sets, and one of them was empty temporarily (I removed its bindings temporarily and was going to use it for something again later). The crash reliably occurred when I did above a certain number of draw calls, and always at the same number. My band-aid fix was to put a dummy buffer in the descriptor set, which seems to prevent the issue.

The specific panic I was getting was:

```
thread 'main' panicked at 'All the descriptors count of a pool are 0', .\vulkano-0.24.0\src\descriptor\descriptor_set\sys.rs:300:9
stack backtrace:
   0: std::panicking::begin_panic<str>
             at .\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:519
   1: vulkano::descriptor::descriptor_set::sys::UnsafeDescriptorPool::new
             at .\vulkano-0.24.0\src\descriptor\descriptor_set\sys.rs:300
   2: vulkano::descriptor::descriptor_set::std_pool::{{impl}}::alloc
             at .\vulkano-0.24.0\src\descriptor\descriptor_set\std_pool.rs:115
   3: vulkano::descriptor::descriptor_set::persistent::PersistentDescriptorSetBuilder<tuple<>>::build_with_pool<tuple<>,alloc::sync::Arc<vulkano::descriptor::descriptor_set::std_pool::StdDescriptorPool>>
             at .\vulkano-0.24.0\src\descriptor\descriptor_set\persistent.rs:224
   4: vulkano::descriptor::descriptor_set::persistent::PersistentDescriptorSetBuilder<tuple<>>::build<tuple<>>
             at .\vulkano-0.24.0\src\descriptor\descriptor_set\persistent.rs:191
```

**Comment by Tenebryo** [comment]
I wrote a minimal example of the issue: https://gist.github.com/Tenebryo/8a0bb1015f4c7b847983ba3a4c4631f6

As is, it crashes on my computer with the backtrace bellow. There are no issues if lines 148 and 290 are uncommented, however.

```
thread 'main' panicked at 'All the descriptors count of a pool are 0', ~\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.24.0\src\descriptor\descriptor_set\sys.rs:300:9
stack backtrace:
   0: std::panicking::begin_panic<str>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:519
   1: vulkano::descriptor::descriptor_set::sys::UnsafeDescriptorPool::new
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.24.0\src\descriptor\descriptor_set\sys.rs:300
   2: vulkano::descriptor::descriptor_set::std_pool::{{impl}}::alloc
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.24.0\src\descriptor\descriptor_set\std_pool.rs:115
   3: vulkano::descriptor::descriptor_set::persistent::PersistentDescriptorSetBuilder<tuple<>>::build_with_pool<tuple<>,alloc::sync::Arc<vulkano::descriptor::descriptor_set::std_pool::StdDescriptorPool>>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.24.0\src\descriptor\descriptor_set\persistent.rs:224
   4: vulkano::descriptor::descriptor_set::persistent::PersistentDescriptorSetBuilder<tuple<>>::build<tuple<>>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.24.0\src\descriptor\descriptor_set\persistent.rs:191
   5: vulkano_issue1632::main::{{closure}}
             at .\src\main.rs:306
   6: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<tuple<>,closure-2>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:206
   7: alloc::boxed::{{impl}}::call_mut<tuple<winit::event::Event<tuple<>>, mut winit::event_loop::ControlFlow*>,FnMut<tuple<winit::event::Event<tuple<>>, mut winit::event_loop::ControlFlow*>>,alloc::alloc::Global>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc\src\boxed.rs:1553
   8: winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<tuple<>>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:245
   9: std::panic::{{impl}}::call_once<tuple<>,closure-0>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:344
  10: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:379
  11: winit::platform_impl::platform::drop_handler::{{impl}}::drop
  12: std::panicking::try<tuple<>,std::panic::AssertUnwindSafe<closure-0>>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:343
  13: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:431
  14: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,tuple<>,closure-0>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:152
  15: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::call_event_handler<tuple<>>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:239
  16: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::call_redraw_events_cleared<tuple<>>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:404
  17: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::move_state_to<tuple<>>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:355
  18: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::redraw_events_cleared<tuple<>>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:231
  19: winit::platform_impl::platform::event_loop::public_window_callback_inner::{{closure}}<tuple<>>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:894
  20: core::ops::function::FnOnce::call_once<closure-0,tuple<>>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  21: std::panic::{{impl}}::call_once<isize,closure-0>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:344
  22: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,isize>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:379
  23: hashbrown::raw::RawIterHash<tuple<tuple<usize, usize>, tuple<>>, alloc::alloc::Global>::new<tuple<tuple<usize, usize>, tuple<>>,alloc::alloc::Global>
  24: std::panicking::try<isize,std::panic::AssertUnwindSafe<closure-0>>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:343
  25: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,isize>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:431
  26: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,isize,closure-0>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:152
  27: winit::platform_impl::platform::event_loop::public_window_callback_inner<tuple<>>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:1980
  28: winit::platform_impl::platform::event_loop::public_window_callback<tuple<>>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:791
  29: DefSubclassProc
  30: DefSubclassProc
  31: CallWindowProcW
  32: CallWindowProcW
  33: glPushClientAttrib
  34: CallWindowProcW
  35: DispatchMessageW
  36: SendMessageTimeoutW
  37: KiUserCallbackDispatcher
  38: NtUserDispatchMessage
  39: DispatchMessageW
  40: winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run_return<tuple<>,closure-2>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:221
  41: winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-2>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:191
  42: winit::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-2>
             at ~\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\event_loop.rs:154
  43: vulkano_issue1632::main
             at .\src\main.rs:233
  44: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at ~\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
```

**Comment by Rua** [comment]
@AustinJ235 since you worked on descriptor sets recently, can you look into this?

**Comment by AustinJ235** [comment]
This is expected behavior. There seems to be a bit of a gap in the vulkan spec in this regard. `DescriptorSetLayout` can be valid with no descriptors; however, `DescriptorPool` requires there to be at least one descriptor.

`VkDescriptorSetLayoutCreateInfo`
```
VUID-VkDescriptorSetLayoutCreateInfo-pBindings-parameter
If bindingCount is not 0, pBindings must be a valid pointer to an array of bindingCount valid VkDescriptorSetLayoutBinding structures
```

`VkDescriptorPoolCreateInfo`
```
VUID-VkDescriptorPoolCreateInfo-pPoolSizes-parameter
pPoolSizes must be a valid pointer to an array of poolSizeCount valid VkDescriptorPoolSize structures

VUID-VkDescriptorPoolCreateInfo-poolSizeCount-arraylength
poolSizeCount must be greater than 0
```

`VkDescriptorPoolSize`
```
VUID-VkDescriptorPoolSize-descriptorCount-00302
descriptorCount must be greater than 0
```

This error would occur in `StdDescriptorPool` when an allocation attempt is made with a layout of no size and when it is unable to find space in any of the existing pools (max set count reached). It will try to create one with the descriptor count * 40 which in this case is still 0.

Either we can add a dummy descriptor to empty layouts, or we can disallow allocation of empty descriptor layouts.

**Comment by Rua** [comment]
Maybe just reallocate another pool with the same counts as the previous one, in this case?

The implementation could also "cheat". An empty descriptor set contains no data, which means that from the point of view of Vulkan, all empty descriptor sets are created equal and are interchangeable. The user only ever needs exactly *one* such descriptor set, and could reuse it infinitely. I imagine there's various ways to go about it, it's just a possible line of investigation.

**Comment by ColonelThirtyTwo** [comment]
Just ran into this. At the very least, an improved error message or a comment on the failing assertion would be helpful.
