### ISSUE TITLE
Vulkano Examples fail to compile on clean ubuntu

### ISSUE THREAD

**Issue by Firestar99** [vulkano-rs/vulkano#1955]
# Template

*   Version of vulkano: current git master (3bbd124ab96ad24c81f494be1c999e1730964c6b)
*   OS: Ubuntu 22.04
*   GPU (the selected PhysicalDevice): N/A
*   GPU Driver: N/A
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: N/A

# Issue

Cloning the Vulkano git repo and trying to build fails on a clean Ubuntu 22.04 with the packages described below installed. Note that this is specific to the /examples project, normal vulkano lib as a dependency does builds. On a previous older installation it ran just fine. Likely some missing library or so, which I fail to track down.

1. Clean Kubuntu 22.04 (KDE Plasma desktop)
2. installed latest stable rust via rustup
3. installed via apt: build-essential git python cmake libvulkan-dev vulkan-utils
    Note: python package is deprecated, just use python3 instead which is even preinstalled
4. clone git master and cargo run.

Output (some details omitted by me):
```
error: failed to run custom build command for `servo-fontconfig-sys v5.1.0`
Caused by:
  process didn't exit successfully: `/home/[...]/workspace/frameworks/vulkano/target/debug/build/servo-fontconfig-sys-f44f4193508fcbf8/build-script-build` (exit status: 101)
  --- stdout
  [...]
  --- stderr
  thread 'main' panicked at 'Could not run `"pkg-config" "--libs" "--cflags" "fontconfig" "fontconfig >= 2.11.1"`
  The pkg-config command could not be found.
  Most likely, you need to install a pkg-config package for your OS.
  Try `apt install pkg-config`, or `yum install pkg-config`,
  or `pkg install pkg-config` depending on your distribution.
  If you've already installed it, ensure the pkg-config command is one of the
  directories in the PATH environment variable.
  If you did not expect this build to link to a pre-installed system library,
  then check documentation of the servo-fontconfig-sys crate for an option to
  build the library from source, or disable features or dependencies
  that require pkg-config.', /home/[...]/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-fontconfig-sys-5.1.0/build.rs:34:17
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
     2: core::panicking::panic_display
               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:72:5
     3: build_script_build::main
               at ./build.rs:34:17
     4: core::ops::function::FnOnce::call_once
               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

That output very clearly says I need to install pkg-config, which is not specified in the setup documentation :D but anyways after installing it continues to fail:

```
error: failed to run custom build command for `servo-fontconfig-sys v5.1.0`
Caused by:
  process didn't exit successfully: `/home/[...]/workspace/frameworks/vulkano/target/debug/build/servo-fontconfig-sys-f44f4193508fcbf8/build-script-build` (exit status: 101)
  --- stdout
  [...]
  --- stderr
  thread 'main' panicked at '`"pkg-config" "--libs" "--cflags" "fontconfig" "fontconfig >= 2.11.1"` did not exit successfully: exit status: 1
  error: could not find system library 'fontconfig' required by the 'servo-fontconfig-sys' crate
  --- stderr
  Package fontconfig was not found in the pkg-config search path.
  Perhaps you should add the directory containing `fontconfig.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'fontconfig' found
  Package fontconfig was not found in the pkg-config search path.
  Perhaps you should add the directory containing `fontconfig.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'fontconfig' found
  ', /home/[...]/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-fontconfig-sys-5.1.0/build.rs:34:17
  stack backtrace:
  [...] (same backtrace)
```

This time it clearly states that it's missing fontconfig, so let's install it:

```
fontconfig is already the newest version (2.13.1-4.2ubuntu5).
```

And now I'm stuck, cause I don't know why it's complaining or how to fix it. I'm not familiar with the rust build toolchain or the gnu / C++ / pkg-config build toolchain. Any help is appreciated :D

**Comment by AustinJ235** [comment]
You'll need to have `libfontconfig-dev` also.

**Comment by Firestar99** [comment]
Thanks that did it :D
