### ISSUE TITLE
Triangle example crashes on wayland when resizing window

### ISSUE THREAD

**Issue by MelonenBiber** [vulkano-rs/vulkano#2238]
# Triangle example crashes on wayland when resizing window

*   Version of vulkano: 0.33.0 (https://github.com/vulkano-rs/vulkano/tree/c1c188b00cc586ae6570ad300e652b78d9c01672)
*   OS: Fedora 38 / Linux 6.3.8-200.fc38.x86_64 / Wayland (Gnome 44.2)
*   GPU (the selected PhysicalDevice): NVIDIA GeForce GTX 1060 6GB
*   GPU Driver: Nvidia 535.54.03

# How to reproduce:
```
git clone https://github.com/vulkano-rs/vulkano/ 
cd vulkano
git checkout c1c188b00cc586ae6570ad300e652b78d9c01672
RUST_BACKTRACE=full cargo run --bin triangle --release
```
Now grab a window edge and rapidly drag it left and right for a couple seconds until it crashes

# Info
## If there is any additional info I can provide that may help feel free to tell me

I could only observe this on wayland, in X11 the example just made my pc lag a lot (no idea if this is related).

I have little prior experience with low level graphics programming, therefore I can't say if this is vulkanos fault but I don't have problems resizing any other window.

Before the program crashes everything graphical freezes as well (other windows, cursor, etc.), but sound continues to play.

The gpu usage seems to spike during the graphical freeze:

![image](https://github.com/vulkano-rs/vulkano/assets/45320352/9d2e8e7f-2726-49a1-ade0-71f0f779c0f1)

Also here is the stacktrace:
```Using device: NVIDIA GeForce GTX 1060 6GB (type: DiscreteGpu)
thread 'main' panicked at 'unexpected error: DeviceLost', vulkano/src/lib.rs:581:18
stack backtrace:
   0:     0x55c9cd38ab5a - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5dat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55c9cd38ab5a - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886bat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55c9cd38ab5a - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55c9cd38ab5a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55c9cd3afc4f - core::fmt::write::h9ffde816c577717bat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:     0x55c9cd387ce5 - std::io::Write::write_fmt::h88186074961638e4at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:     0x55c9cd38a925 - std::sys_common::backtrace::_print::h184198273ed08d59at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55c9cd38a925 - std::sys_common::backtrace::print::h1b4d8e7add699453at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55c9cd38beae - std::panicking::default_hook::{{closure}}::h393bcea75423915aat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:     0x55c9cd38bc55 - std::panicking::default_hook::h48c64f31d8b3fd03at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:     0x55c9cd38c40e - std::panicking::rust_panic_with_hook::hafdc493a79370062at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
  11:     0x55c9cd38c309 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
  12:     0x55c9cd38afc6 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x55c9cd38c062 - rust_begin_unwindat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  14:     0x55c9cd06d9c3 - core::panicking::panic_fmt::h0f6ef0178afce4f2at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  15:     0x55c9cd2ba306 - vulkano::device::queue::QueueState::wait_idle::h0ef1b533027b390a
  16:     0x55c9cd0737cd - <vulkano::swapchain::acquire_present::PresentFuture<P> as core::ops::drop::Drop>::drop::h53cd8554cb487fc7
  17:     0x55c9cd09aeec - core::ptr::drop_in_place<vulkano::swapchain::acquire_present::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<dyn vulkano::sync::future::GpuFuture>,vulkano::swapchain::acquire_present::SwapchainAcquireFuture>>>>::h4aa50e3e0a5f75d0
  18:     0x55c9cd0a2195 - vulkano::sync::future::fence_signal::FenceSignalFuture<F>::flush_impl::h981e2f794dfe7cf0
  19:     0x55c9cd0e2278 - triangle::main::{{closure}}::h6967ca5ffa03b461
  20:     0x55c9cd0dd9ed - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run::h3496663a12d51aa3
  21:     0x55c9cd0db90c - winit::platform_impl::platform::EventLoop<T>::run::h2ca087afe1a9ae2f
  22:     0x55c9cd0d34d7 - triangle::main::h2d4a2eb73c844d5e
  23:     0x55c9cd0fee13 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2aa900ac11dc6712
  24:     0x55c9cd0ff0c9 - std::rt::lang_start::{{closure}}::h47c16b7c69c3e061
  25:     0x55c9cd383aee - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb1327dc2ef3fecdfat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
  26:     0x55c9cd383aee - std::panicking::try::do_call::h4044173225fe83ddat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  27:     0x55c9cd383aee - std::panicking::try::hd8a722c09d156a53at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  28:     0x55c9cd383aee - std::panic::catch_unwind::hd2ca07971cf0119bat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  29:     0x55c9cd383aee - std::rt::lang_start_internal::{{closure}}::h26d89d595cf47b70at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
  30:     0x55c9cd383aee - std::panicking::try::do_call::hf47aa1aa005e5f1aat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  31:     0x55c9cd383aee - std::panicking::try::h73d246b2423eaf4eat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  32:     0x55c9cd383aee - std::panic::catch_unwind::hbaaeae8f1b2f9915at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  33:     0x55c9cd383aee - std::rt::lang_start_internal::h76f3e81e6b8f13f9at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
  34:     0x55c9cd0d40e5 - main
  35:     0x7f34bba41b4a - __libc_start_call_main
  36:     0x7f34bba41c0b - __libc_start_main@@GLIBC_2.34
  37:     0x55c9cd06dfb5 - _start
  38:                0x0 - <unknown>
thread 'main' panicked at 'unexpected error: DeviceLost', vulkano/src/lib.rs:581:18
stack backtrace:
   0:     0x55c9cd38ab5a - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5dat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55c9cd38ab5a - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886bat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55c9cd38ab5a - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55c9cd38ab5a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55c9cd3afc4f - core::fmt::write::h9ffde816c577717bat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:     0x55c9cd387ce5 - std::io::Write::write_fmt::h88186074961638e4at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:     0x55c9cd38a925 - std::sys_common::backtrace::_print::h184198273ed08d59at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55c9cd38a925 - std::sys_common::backtrace::print::h1b4d8e7add699453at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55c9cd38beae - std::panicking::default_hook::{{closure}}::h393bcea75423915aat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:     0x55c9cd38bc55 - std::panicking::default_hook::h48c64f31d8b3fd03at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:     0x55c9cd38c40e - std::panicking::rust_panic_with_hook::hafdc493a79370062at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
  11:     0x55c9cd38c309 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
  12:     0x55c9cd38afc6 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x55c9cd38c062 - rust_begin_unwindat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  14:     0x55c9cd06d9c3 - core::panicking::panic_fmt::h0f6ef0178afce4f2at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  15:     0x55c9cd2ba306 - vulkano::device::queue::QueueState::wait_idle::h0ef1b533027b390a
  16:     0x55c9cd0eea28 - alloc::sync::Arc<T>::drop_slow::hd46613928db417f2
  17:     0x55c9cd0d6869 - core::ptr::drop_in_place<triangle::main::{{closure}}>::h93a0cb87a00ce9ea
  18:     0x55c9cd0de1ef - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run::h3496663a12d51aa3
  19:     0x55c9cd0db90c - winit::platform_impl::platform::EventLoop<T>::run::h2ca087afe1a9ae2f
  20:     0x55c9cd0d34d7 - triangle::main::h2d4a2eb73c844d5e
  21:     0x55c9cd0fee13 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2aa900ac11dc6712
  22:     0x55c9cd0ff0c9 - std::rt::lang_start::{{closure}}::h47c16b7c69c3e061
  23:     0x55c9cd383aee - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb1327dc2ef3fecdfat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
  24:     0x55c9cd383aee - std::panicking::try::do_call::h4044173225fe83ddat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  25:     0x55c9cd383aee - std::panicking::try::hd8a722c09d156a53at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  26:     0x55c9cd383aee - std::panic::catch_unwind::hd2ca07971cf0119bat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  27:     0x55c9cd383aee - std::rt::lang_start_internal::{{closure}}::h26d89d595cf47b70at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
  28:     0x55c9cd383aee - std::panicking::try::do_call::hf47aa1aa005e5f1aat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  29:     0x55c9cd383aee - std::panicking::try::h73d246b2423eaf4eat /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  30:     0x55c9cd383aee - std::panic::catch_unwind::hbaaeae8f1b2f9915at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  31:     0x55c9cd383aee - std::rt::lang_start_internal::h76f3e81e6b8f13f9at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
  32:     0x55c9cd0d40e5 - main
  33:     0x7f34bba41b4a - __libc_start_call_main
  34:     0x7f34bba41c0b - __libc_start_main@@GLIBC_2.34
  35:     0x55c9cd06dfb5 - _start
  36:                0x0 - <unknown>
thread panicked while panicking. aborting.
[1]    149242 IOT instruction (core dumped)  RUST_BACKTRACE=full cargo run --bin triangle --release
```

**Comment by Rua** [comment]
Do you get any validation errors before the crash?

**Comment by MelonenBiber** [comment]
I'm guessing they are printed to stdout/stderr?
If so, no the stacktrace is the only output i got apart from the expected example output ```Using device: NVIDIA GeForce GTX 1060 6GB (type: DiscreteGpu)```

**Comment by Rua** [comment]
I mean, if you activate the validation layer, does it say anything?

**Comment by MelonenBiber** [comment]
How do I activate the validation layer?

**Comment by MelonenBiber** [comment]
This is all of the output split up in before and after the crash in case thats helpful
```
UNASSIGNED-khronos-validation-createinstance-status-message(INFO / SPEC): msgNum: -671457468 - Validation Information: [ UNASSIGNED-khronos-validation-createinstance-status-message ] Object 0: handle = 0x55ac2a15c160, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xd7fa5f44 | Khronos Validation Layer Active:
    Settings File: Found at /home/melon/.local/share/vulkan/settings.d/vk_layer_settings.txt specified by VkConfig application override.
    Current Enables: None.
    Current Disables: VK_VALIDATION_FEATURE_DISABLE_THREAD_SAFETY_EXT.

    Objects: 1
        [0] 0x55ac2a15c160, type: 1, name: NULL
Using device: NVIDIA GeForce GTX 1060 6GB (type: DiscreteGpu)
UNASSIGNED-cache-file-error(INFO / SPEC): msgNum: -256165483 - Validation Information: [ UNASSIGNED-cache-file-error ] Object 0: handle = 0x55ac2aadef10, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf0bb3995 | Cannot open shader validation cache at /home/melon/.cache/shader_validation_cache-1000.bin for reading (it may not exist yet)
    Objects: 1
        [0] 0x55ac2aadef10, type: 3, name: NULL
```
```
VUID-vkQueueSubmit-pCommandBuffers-00071(ERROR / SPEC): msgNum: 774851941 - Validation Error: [ VUID-vkQueueSubmit-pCommandBuffers-00071 ] Object 0: handle = 0x55ac2aadef10, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x2e2f4d65 | vkQueueSubmit(): pSubmits[0].pCommandBuffers[0] VkCommandBuffer 0x55ac2b284610[] is already in use and is not marked for simultaneous use. The Vulkan spec states: If any element of the pCommandBuffers member of any element of pSubmits was not recorded with the VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT, it must not be in the pending state (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkQueueSubmit-pCommandBuffers-00071)
    Objects: 1
        [0] 0x55ac2aadef10, type: 3, name: NULL
UNASSIGNED-CoreValidation-DrawState-CommandBufferSingleSubmitViolation(ERROR / SPEC): msgNum: -329268476 - Validation Error: [ UNASSIGNED-CoreValidation-DrawState-CommandBufferSingleSubmitViolation ] Object 0: handle = 0x55ac2b284610, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xec5fc304 | VkCommandBuffer 0x55ac2b284610[] was begun w/ VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT set, but has been submitted 0x2times.
    Objects: 1
        [0] 0x55ac2b284610, type: 6, name: NULL
VUID-vkQueueSubmit-pWaitSemaphores-03238(ERROR / SPEC): msgNum: -1258007888 - Validation Error: [ VUID-vkQueueSubmit-pWaitSemaphores-03238 ] Object 0: handle = 0x67eb00000067eb, type = VK_OBJECT_TYPE_SEMAPHORE; Object 1: handle = 0x55ac29ebb410, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xb50452b0 | vkQueueSubmit(): pSubmits[0].pWaitSemaphores[0] Queue VkQueue 0x55ac29ebb410[] is waiting on semaphore (VkSemaphore 0x67eb00000067eb[]) that has no way to be signaled. The Vulkan spec states: All elements of the pWaitSemaphores member of all elements of pSubmits created with a VkSemaphoreType of VK_SEMAPHORE_TYPE_BINARY must reference a semaphore signal operation that has been submitted for execution and any semaphore signal operations on which it depends (if any) must have also been submitted for execution (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkQueueSubmit-pWaitSemaphores-03238)
    Objects: 2
        [0] 0x67eb00000067eb, type: 5, name: NULL
        [1] 0x55ac29ebb410, type: 4, name: NULL
thread 'main' panicked at 'unexpected error: DeviceLost', vulkano/src/lib.rs:581:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'unexpected error: DeviceLost', vulkano/src/lib.rs:581:18
stack backtrace:
   0:     0x55ac28c65b5a - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55ac28c65b5a - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ac28c65b5a - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55ac28c65b5a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55ac28c8ac4f - core::fmt::write::h9ffde816c577717b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:     0x55ac28c62ce5 - std::io::Write::write_fmt::h88186074961638e4
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:     0x55ac28c65925 - std::sys_common::backtrace::_print::h184198273ed08d59
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55ac28c65925 - std::sys_common::backtrace::print::h1b4d8e7add699453
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55ac28c66eae - std::panicking::default_hook::{{closure}}::h393bcea75423915a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:     0x55ac28c66c55 - std::panicking::default_hook::h48c64f31d8b3fd03
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:     0x55ac28c6740e - std::panicking::rust_panic_with_hook::hafdc493a79370062
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
  11:     0x55ac28c67309 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
  12:     0x55ac28c65fc6 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x55ac28c67062 - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  14:     0x55ac289489c3 - core::panicking::panic_fmt::h0f6ef0178afce4f2
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  15:     0x55ac28b95306 - vulkano::device::queue::QueueState::wait_idle::h0ef1b533027b390a
  16:     0x55ac289c9a28 - alloc::sync::Arc<T>::drop_slow::hd46613928db417f2
  17:     0x55ac289b1869 - core::ptr::drop_in_place<triangle::main::{{closure}}>::h93a0cb87a00ce9ea
  18:     0x55ac289b91ef - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run::h3496663a12d51aa3
  19:     0x55ac289b690c - winit::platform_impl::platform::EventLoop<T>::run::h2ca087afe1a9ae2f
  20:     0x55ac289ae4d7 - triangle::main::h2d4a2eb73c844d5e
  21:     0x55ac289d9e13 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2aa900ac11dc6712
  22:     0x55ac289da0c9 - std::rt::lang_start::{{closure}}::h47c16b7c69c3e061
  23:     0x55ac28c5eaee - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb1327dc2ef3fecdf
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
  24:     0x55ac28c5eaee - std::panicking::try::do_call::h4044173225fe83dd
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  25:     0x55ac28c5eaee - std::panicking::try::hd8a722c09d156a53
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  26:     0x55ac28c5eaee - std::panic::catch_unwind::hd2ca07971cf0119b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  27:     0x55ac28c5eaee - std::rt::lang_start_internal::{{closure}}::h26d89d595cf47b70
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
  28:     0x55ac28c5eaee - std::panicking::try::do_call::hf47aa1aa005e5f1a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  29:     0x55ac28c5eaee - std::panicking::try::h73d246b2423eaf4e
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  30:     0x55ac28c5eaee - std::panic::catch_unwind::hbaaeae8f1b2f9915
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  31:     0x55ac28c5eaee - std::rt::lang_start_internal::h76f3e81e6b8f13f9
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
  32:     0x55ac289af0e5 - main
  33:     0x7fb3b3aecb4a - __libc_start_call_main
  34:     0x7fb3b3aecc0b - __libc_start_main@@GLIBC_2.34
  35:     0x55ac28948fb5 - _start
  36:                0x0 - <unknown>
thread panicked while panicking. aborting.
[1]    219397 IOT instruction (core dumped)  ./target/release/triangle
```

**Comment by Gardene-el** [comment]
the crash also happened on x11

**Comment by hYdos** [comment]
This did not crash for me when i was on ubuntu 23 using X11 ~1-2 months ago

**Comment by Gardene-el** [comment]
I retested it and confirmed that it causes temporary stuttering on the laptop's built-in display. Additionally, it leads to the crash of the display on the external monitor connected via HDMI (which requires reconnection).
