### ISSUE TITLE
vulkano panicked when using with rust-gpu

### ISSUE THREAD

**Issue by SSSxCCC** [vulkano-rs/vulkano#2550]
*   Version of vulkano: 0.34.1
*   Version of rust-gpu: 0.9
*   OS: Windows10
*   GPU (the selected PhysicalDevice): Intel Iris Xe Graphics
*   GPU Driver: 31.0.101.5522
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue:

rust-gpu shader:

```rust
#![no_std]

use spirv_std::{glam::{vec4, Vec2, Vec4}, spirv};

#[spirv(vertex)]
pub fn main_vs(
    #[spirv(position, invariant)] out_pos: &mut Vec4,
    position: Vec2,
) {
    *out_pos = position.extend(0.0).extend(1.0);
}

#[spirv(fragment)]
pub fn main_fs(output: &mut Vec4) {
    *output = vec4(1.0, 0.0, 0.0, 1.0);
}
```

vulkano code:

```rust
        const SHADER: &[u8] = include_bytes!(env!("my_shader.spv"));
        let shader_code = SHADER
            .chunks(4)
            .map(|c| u32::from_le_bytes([c[0], c[1], c[2], c[3]]))
            .collect::<Vec<_>>();

        let shader_module = unsafe {
            ShaderModule::new(
                context.device().clone(),
                ShaderModuleCreateInfo::new(&shader_code),
            )
        }
        .unwrap();

        let vs = shader_module.entry_point("main_vs").unwrap();
        let fs = shader_module.entry_point("main_fs").unwrap();

        let vertex_input_state = MyVertex::per_vertex()
            .definition(&vs.info().input_interface) // thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\SxC\.cargo\registry\src\index.crates.io-6f17d22bba15001f\vulkano-0.34.1\src\pipeline\graphics\vertex_input\definition.rs:45:46
            .unwrap();
```

# Issue

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\SxC\.cargo\registry\src\index.crates.io-6f17d22bba15001f\vulkano-0.34.1\src\pipeline\graphics\vertex_input\definition.rs:45:46

**Comment by SSSxCCC** [comment]
I add SpirvMetadata::NameVariables in build.rs and this issue is fixed. Thank you so much!

```rust
use spirv_builder::{MetadataPrintout, SpirvBuilder, SpirvMetadata};
use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    SpirvBuilder::new("minimal-shader", "spirv-unknown-vulkan1.2")
        .spirv_metadata(SpirvMetadata::NameVariables) // this fix this issue
        .print_metadata(MetadataPrintout::Full)
        .build()?;

    Ok(())
}
```

**Comment by SSSxCCC** [comment]
I just started to learn to use rust-gpu, MetadataPrintout::Full is copied from somewhere else. I just delete '.print_metadata(MetadataPrintout::Full)' and the code also works fine, thanks again!

**Comment by SSSxCCC** [comment]
I just notified that print_metadata is set to MetadataPrintout::Full in SpirvBuilder::new. So deleting '.print_metadata(MetadataPrintout::Full)' changes nothing.

I tried to change MetadataPrintout::Full to MetadataPrintout::DependencyOnly, but this resulted in a compilation error:

```
error: environment variable `minimal_shader.spv` not defined at compile time
   --> minimal\src\triangle_renderer.rs:132:46
    |
132 |         const SHADER: &[u8] = include_bytes!(env!("minimal_shader.spv"));
    |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: use `std::env::var("minimal_shader.spv")` to read the variable at run time
    = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by Firestar99** [comment]
I've made a small sample project on how to integrate vulkano and rust-gpu, feel free to reference: https://github.com/Firestar99/rust-gpu-vulkano-example

The build script I'm using configures `spirv-builder` like this:
https://github.com/Firestar99/rust-gpu-vulkano-example/blob/eeb8b3ddf4cd475bd24ba58470f9c8b363334228/example/build.rs#L18-L21
* multimodule so that every shader has a separate spv file, it will work without, but almost all tooling expects one shader per spv file. And `shader!` codegen may generate the same struct multiple times resulting in compile errors, if you [didn't disable it](https://github.com/vulkano-rs/vulkano/pull/2482) (currently only master).
* print_metadata: if you use a build script and you don't emit any `cargo::rerun-if-changed=./path`, cargo will only rerun your build script if the script or the contents of `src` changed. Which means if you only change your shaders, or dependencies that only your shaders depend upon, your shaders won't be recompiled and you'll be confused on why yout changes don't do anything. `MetadataPrintout::DependencyOnly` makes rust-gpu emit this rerun metadata for cargo on it's own, without you having to care for it at all, and you'll always have up-to-date shaders.

**Comment by Firestar99** [comment]
Also feel free to steal the codegen of my main project, which generates a single file containing each shader entry point as a separate `shader!` macro invocation with the correct path, all of them organized in the same `mod` structure as your shader crate. But I haven't gotten around to clean it up enough to release it publicly, though that may happen in a few months as I want to publish a bindless API for rust-gpu and vulkano (potentially wgpu as well?).
https://gitlab.com/spacegamedev/space-rust/-/tree/master/vulkano-bindless/vulkano-bindless-shader-builder?ref_type=heads
