### ISSUE TITLE
Second descriptor set fails at runtime

### ISSUE THREAD

**Issue by SiebenCorgie** [vulkano-rs/vulkano#732]
Hi,

Earlier this day I asked how to send multiple textures to the GPU. Now I tried to create a second descriptor set for my `draw_indexed()` function. This looks something like this:
```
        //first, create the sampler
        let sampler_albedo_tmp = vulkano::sampler::Sampler::new(
            device.clone(),
            vulkano::sampler::Filter::Linear,
            vulkano::sampler::Filter::Linear,
            vulkano::sampler::MipmapMode::Nearest,
            vulkano::sampler::SamplerAddressMode::Repeat,
            vulkano::sampler::SamplerAddressMode::Repeat,
            vulkano::sampler::SamplerAddressMode::Repeat,
            0.0, 1.0, 0.0, 0.0
        ).expect("Failed to generate albedo sampler");

        //load texture
        let (texture_albedo, tex_future_albedo) = {
            let image = image::load_from_memory_with_format(include_bytes!("/home/siebencorgie/Scripts/Rust/engine/ori-engine/data/fallback_alb.png"),
                image::ImageFormat::PNG).expect("failed to load png").to_rgba();

            let (width, height) = image.dimensions();
            let image_data = image.into_raw().clone();

            vulkano::image::immutable::ImmutableImage::from_iter(
                image_data.iter().cloned(),
                vulkano::image::Dimensions::Dim2d { width: width, height: height },
                vulkano::format::R8G8B8A8Srgb,
                Some(queue.family()),
                queue.clone()).expect("failed to create immutable image")
        };


        //Index 1 because the other set is at index 0
        let set_02 = Arc::new(
            PersistentDescriptorSet::start(pipeline.clone(), 1)
            .add_sampled_image(self.t_albedo.clone(), self.sampler_albedo.clone())
            .expect("failed to add sampled albedo")
            .build().expect("failed to build set_02")
        );
```
However, if I submit it to my command buffer (it's actually several time if that matter, but it didn't with the first set) like this:
```
                    .draw_indexed(
                        pipeline,

                        vulkano::command_buffer::DynamicState{
                            line_width: None,
                            viewports: Some(vec![vulkano::pipeline::viewport::Viewport {
                                origin: [0.0, 0.0],
                                dimensions: [dimensions[0] as f32, dimensions[1] as f32],
                                depth_range: 0.0 .. 1.0,
                            }]),
                            scissors: None,
                        },
                        vertex_buffer,

                        index_buffer,

                        (set_01, set_02),

                        ()
                    )
```
I get a runtime error:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', /home/siebencorgie/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.5.6/src/buffer/cpu_pool.rs:603:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
```

The only reason I could think of is, that I don't use the `texture_future` atm. to clean the unused resources.
Just for reference, my glsl shaders:

Vertex
```
#version 450

layout(location = 0) in vec3 position;
layout(location = 1) in vec2 tex_coord;
layout(location = 2) in vec3 normal;
layout(location = 3) in vec3 tangent;
layout(location = 4) in vec3 color;

layout(location = 0) out vec3 v_normal;
layout(location = 1) out vec2 tex_coordinates;


layout(set = 0, binding = 0) uniform Data {
    mat4 model;
    mat4 view;
    mat4 proj;
} u_main;

void main() {
    mat4 modelview = u_main.view * u_main.model;
    v_normal = transpose(inverse(mat3(modelview))) * normal;
    gl_Position = u_main.proj * modelview * vec4(position, 1.0);
    tex_coordinates = tex_coord;
}
```
Fragment
```
#version 450

layout(location = 0) in vec3 v_normal;
layout(location = 1) in vec2 tex_coordinates;


layout(location = 0) out vec4 f_color;

layout(set = 1, binding = 0) uniform sampler2D tex;

const vec3 LIGHT = vec3(0.0, -1.0, 1.0);

void main() {
    float brightness = dot(normalize(v_normal), normalize(LIGHT));
    vec3 dark_color = vec3(0.6, 0.0, 0.0);
    vec3 regular_color = vec3(1.0, 0.0, 0.0);
    f_color = vec4(texture(tex, tex_coordinates).xyz * brightness, 1.0);
}
```

Sorry for the potential noob question, any help is appreciated!

-Siebencorgie

**Comment by tomaka** [comment]
The error is probably simply #725.
At some place you're probably calling `pool.chunk()` with an empty iterator, and that causes it.

**Comment by SiebenCorgie** [comment]
I searched in my project but didn't find any `.chunk()`. Is there another reason for this error?
Things I could think of are:

- `(set_01, set_02)` doesn't work in `draw_indexed()`
- I don't `cleanup()` the texture_future
- some other reason for the shader to fail (linking maybe?)

**Comment by tomaka** [comment]
My bad, I thought I recognized the failed assertion but it's not the line of code that was thinking of.

The error indicates that the buffer wasn't unlocked before being reclaimed.
It's clearly a bug somewhere in vulkano.

Chance are however that you are finding out about that bug by doing something weird in your code, even though I don't know what.

**Comment by SiebenCorgie** [comment]
Okay, I'll have a look if I find some kind of locking issue. If so, I'll let you know, If not I'll try to find another way. 
Thanks for your help!

**Comment by SiebenCorgie** [comment]
I changed my system to create the descriptor set for the texture just once, and then clone it several times, once for each mesh i want to render (so once per `draw_indexed()`).
The panic is still there, but I get a stack back trace now, maybe you can work with it, for me it's unreadable:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', /home/siebencorgie/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.5.6/src/buffer/cpu_pool.rs:603:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /checkout/src/libcore/result.rs:860:4
stack backtrace:
   0:       0xbdcf282da3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h6f92a98ef8e5eae4
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:       0xbdcf27f3a4 - std::sys_common::backtrace::_print::h489cd0eefa05c32d
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:       0xbdcf284fb3 - std::panicking::default_hook::{{closure}}::h13d1da800600c86b
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:380
   3:       0xbdcf284d12 - std::panicking::default_hook::h983308b4dff4785d
                               at /checkout/src/libstd/panicking.rs:396
   4:       0xbdcf2854b7 - std::panicking::rust_panic_with_hook::hccdc1ece2b7bc9bd
                               at /checkout/src/libstd/panicking.rs:610
   5:       0xbdcf285384 - std::panicking::begin_panic::h4f27e07814aa7683
                               at /checkout/src/libstd/panicking.rs:571
   6:       0xbdcf285289 - std::panicking::begin_panic_fmt::h8610e9c65ca654cd
                               at /checkout/src/libstd/panicking.rs:521
   7:       0xbdcf28521a - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:497
   8:       0xbdcf2b23a0 - core::panicking::panic_fmt::h343ad6ea5a71a492
                               at /checkout/src/libcore/panicking.rs:71
   9:       0xbdced49dac - core::result::unwrap_failed::hc1d3d296c7ba32e5
                               at /checkout/src/libcore/macros.rs:31
  10:       0xbdcec94cab - <core::result::Result<T, E>>::unwrap::haf66de02c9bf5c9e
                               at /checkout/src/libcore/result.rs:738
  11:       0xbdceba6e9f - <vulkano::buffer::cpu_pool::CpuBufferPoolChunk<T, A> as core::ops::drop::Drop>::drop::h9e918a5053b252f0
                               at /home/siebencorgie/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.5.6/src/buffer/cpu_pool.rs:597
  12:       0xbdced12994 - core::ptr::drop_in_place::he0ead5efa505855c
                               at /checkout/src/libcore/ptr.rs:61
  13:       0xbdced08714 - core::ptr::drop_in_place::h795bfbfadc6b82a1
                               at /checkout/src/libcore/ptr.rs:61
  14:       0xbdced05b44 - core::ptr::drop_in_place::h6115ae0c6fbc68bc
                               at /checkout/src/libcore/ptr.rs:61
  15:       0xbdced14a74 - core::ptr::drop_in_place::hf524e89863575d70
                               at /checkout/src/libcore/ptr.rs:61
  16:       0xbdced10559 - core::ptr::drop_in_place::hc80918e329a01634
                               at /checkout/src/libcore/ptr.rs:61
  17:       0xbdcebf905b - <alloc::arc::Arc<T>>::drop_slow::hc6a004d530301cbf
                               at /checkout/src/liballoc/arc.rs:505
  18:       0xbdcedc7196 - <alloc::arc::Arc<T> as core::ops::drop::Drop>::drop::had62fb37aaafa742
                               at /checkout/src/liballoc/arc.rs:821
  19:       0xbdced03054 - core::ptr::drop_in_place::h46a6a6bf1e199b5e
                               at /checkout/src/libcore/ptr.rs:61
  20:       0xbdced11616 - core::ptr::drop_in_place::hd2fdba5ae2fccae9
                               at /checkout/src/libcore/ptr.rs:61
  21:       0xbdced11616 - core::ptr::drop_in_place::hd2fdba5ae2fccae9
                               at /checkout/src/libcore/ptr.rs:61
  22:       0xbdcedda77f - <smallvec::SmallVec<A> as core::ops::drop::Drop>::drop::h845788f9f1dd41be
                               at /home/siebencorgie/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-0.3.3/lib.rs:705
  23:       0xbdced0d984 - core::ptr::drop_in_place::hb021d339cea5cc57
                               at /checkout/src/libcore/ptr.rs:61
  24:       0xbdced11704 - core::ptr::drop_in_place::hd35650d8f58ccf9e
                               at /checkout/src/libcore/ptr.rs:61
  25:       0xbdced099c6 - core::ptr::drop_in_place::h85b620c52b26818f
                               at /checkout/src/libcore/ptr.rs:61
  26:       0xbdced06147 - core::ptr::drop_in_place::h64a8eeec6f7e7194
                               at /checkout/src/libcore/ptr.rs:61
  27:       0xbdcedc87a1 - <alloc::vec::Vec<T> as core::ops::drop::Drop>::drop::h93d344898342e70e
                               at /checkout/src/liballoc/vec.rs:2047
  28:       0xbdced10304 - core::ptr::drop_in_place::hc6855d9950da7251
                               at /checkout/src/libcore/ptr.rs:61
  29:       0xbdced0dbf4 - core::ptr::drop_in_place::hb1694df919756a90
                               at /checkout/src/libcore/ptr.rs:61
  30:       0xbdced0da88 - core::ptr::drop_in_place::hb0c7b12e16e0ee0c
                               at /checkout/src/libcore/ptr.rs:61
  31:       0xbdcebf9a9b - <alloc::arc::Arc<T>>::drop_slow::heee88f315fc2e388
                               at /checkout/src/liballoc/arc.rs:505
  32:       0xbdcedc6d36 - <alloc::arc::Arc<T> as core::ops::drop::Drop>::drop::h849e9e8c6050227c
                               at /checkout/src/liballoc/arc.rs:821
  33:       0xbdced00ac4 - core::ptr::drop_in_place::h2da93a6551e483f6
                               at /checkout/src/libcore/ptr.rs:61
  34:       0xbdced075ff - core::ptr::drop_in_place::h70bbe0334ba888b4
                               at /checkout/src/libcore/ptr.rs:61
  35:       0xbdcecfeb34 - core::ptr::drop_in_place::h19b70132ec9ee69e
                               at /checkout/src/libcore/ptr.rs:61
  36:       0xbdcee4c526 - vulkano::command_buffer::traits::CommandBuffer::execute_after::h46bd239ade43c479
                               at /home/siebencorgie/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.5.6/src/command_buffer/traits.rs:146
  37:       0xbdcee4e6e7 - vulkano::sync::future::GpuFuture::then_execute::h13f0f9c13c536e6a
                               at /home/siebencorgie/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.5.6/src/sync/future/mod.rs:157
  38:       0xbdceecb16a - ori_engine::render::renderer::Renderer::render::h5c37e93624d3b289
                               at /home/siebencorgie/Scripts/Rust/engine/ori-engine/src/render/renderer.rs:450
  39:       0xbdceba1ad3 - simple_scene::main::h4ea3134dc2e97fd5
                               at src/main.rs:44
  40:       0xbdcf28c44c - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  41:       0xbdcf285bdb - std::rt::lang_start::hb2864fffbc1a559d
                               at /checkout/src/libstd/panicking.rs:458
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:61
  42:       0xbdceba1ee2 - main
  43:     0x7f3aeeb8b4c9 - __libc_start_main
  44:       0xbdceb6e889 - _start
  45:                0x0 - <unknown>
thread panicked while panicking. aborting.
```

**Comment by tomaka** [comment]
Executing the command buffer returns an error, probably because there's a problem in the way you use your resources.

Then the panic happens during the cleanup phase.
Probably caused by https://github.com/vulkano-rs/vulkano/blob/ae51cd154f83c2ef50b482e375fb2058d0195d7e/vulkano/src/command_buffer/synced/base.rs#L1021

**Comment by tomaka** [comment]
#733 should remove the panic.

**Comment by SiebenCorgie** [comment]
Yesterday night I added the vulkan validation layers. They report wrong alignment between the first and second descriptor set, followed by the 
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`'
```
error. I can sent you the validation layer error tomorrow if you want.

I also changed my `material` definition to only generate one descriptor set per material for each set, the first and the second one. Then I clone the set for each `draw_indexed()` in the commmand buffer. The rest is more or less the same like in the examples.

**Comment by tomaka** [comment]
I merged #733 so that you can stop trying to randomly guess.
Modify your Cargo.toml to use the github version of vulkano (`vulkano = { git = "https://github.com/vulkano-rs/vulkano" }`) and the panic should go away.

**Comment by SiebenCorgie** [comment]
Thanks! I'll do.

**Comment by SiebenCorgie** [comment]
Hi, 
Sorry to come back, but the problem changed. Now I use the git version of Vulkano. The panic occurs on an unwrap within Vulkano I think (I usually use expect() ).
But today I can send you the Vulkan debug messages:

This is the output when executing `draw_indexed()`
```
ObjectTracker information: OBJ[0x46] : CREATE Buffer object 0x3b
DS information: Descriptor Set 0x37 bound on pipeline VK_PIPELINE_BIND_POINT_GRAPHICS
DS information: Descriptor Set 0x24 bound on pipeline VK_PIPELINE_BIND_POINT_GRAPHICS
DS warning: Additional bits in Source accessMask 0x790 [VK_ACCESS_INPUT_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT] are specified when layout is VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL.

```
after this, it tries to flush which gives the following output, finished with the panic:
```
ObjectTracker information: OBJ_STAT Destroy CommandBuffer obj 0x7f26f5301000 (39 total objs remain & 2 CommandBuffer objs).
ObjectTracker information: OBJ_STAT Destroy CommandPool obj 0x35 (38 total objs remain & 2 CommandPool objs).
ObjectTracker information: OBJ_STAT Destroy CommandBuffer obj 0x7f26f53f0000 (37 total objs remain & 1 CommandBuffer objs).
ObjectTracker information: OBJ_STAT Destroy CommandPool obj 0x3a (36 total objs remain & 1 CommandPool objs).
ObjectTracker information: OBJ_STAT Destroy Buffer obj 0x3b (35 total objs remain & 3 Buffer objs).
thread 'main' panicked at 'failed to execute buffer!: AccessError(BufferNotInitialized)', /checkout/src/libcore/result.rs:860:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
ObjectTracker information: OBJ_STAT Destroy CommandBuffer obj 0x7f26f53cd000 (34 total objs remain & 0 CommandBuffer objs).
ObjectTracker information: OBJ_STAT Destroy CommandPool obj 0x1a (33 total objs remain & 0 CommandPool objs).
ObjectTracker information: OBJ_STAT Destroy Buffer obj 0x16 (32 total objs remain & 2 Buffer objs).
ObjectTracker information: OBJ_STAT Destroy Sampler obj 0x14 (31 total objs remain & 2 Sampler objs).
ObjectTracker information: OBJ_STAT Destroy Sampler obj 0x15 (30 total objs remain & 1 Sampler objs).
ObjectTracker information: OBJ_STAT Destroy DescriptorSet obj 0x37 (29 total objs remain & 1 DescriptorSet objs).
ObjectTracker information: OBJ_STAT Destroy DescriptorPool obj 0x36 (28 total objs remain & 1 DescriptorPool objs).
ObjectTracker information: OBJ_STAT Destroy DescriptorSet obj 0x24 (27 total objs remain & 0 DescriptorSet objs).
ObjectTracker information: OBJ_STAT Destroy DescriptorPool obj 0x23 (26 total objs remain & 0 DescriptorPool objs).
ObjectTracker information: OBJ_STAT Destroy Image obj 0x18 (25 total objs remain & 1 Image objs).
ObjectTracker information: OBJ_STAT Destroy ImageView obj 0x19 (24 total objs remain & 3 ImageView objs).
ObjectTracker information: OBJ_STAT Destroy Sampler obj 0x13 (23 total objs remain & 0 Sampler objs).
ObjectTracker information: OBJ_STAT Destroy Buffer obj 0x34 (22 total objs remain & 1 Buffer objs).
ObjectTracker information: OBJ_STAT Destroy Pipeline obj 0x12 (21 total objs remain & 0 Pipeline objs).
ObjectTracker information: OBJ_STAT Destroy PipelineLayout obj 0x11 (20 total objs remain & 0 PipelineLayout objs).
ObjectTracker information: OBJ_STAT Destroy DescriptorSetLayout obj 0xf (19 total objs remain & 1 DescriptorSetLayout objs).
ObjectTracker information: OBJ_STAT Destroy DescriptorSetLayout obj 0x10 (18 total objs remain & 0 DescriptorSetLayout objs).
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
```
I could not find any problem with the descriptor sets according to the [vulkan specifications](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdBindDescriptorSets-pDescriptorSets-00358). 
As I understand it, the descriptor sets have to be created from the same pipeline-layout, which I somehow do, because I pass the same vulkano-pipeline to the `PersistentDescriptorSet::start()` Once with the `id` 0 and once with the `id` 1.
Vulkano reports the `AccessError(BufferNotInitialized)`, do I have to do something with the texture I pass to the descriptor set, besides creating it with 
```
        let (texture_albedo, tex_future_albedo) = {
            let image = image::load_from_memory_with_format(include_bytes!("/home/siebencorgie/Scripts/Rust/engine/ori-engine/data/fallback_alb.png"),
                image::ImageFormat::PNG).expect("failed to load png").to_rgba();

            let (width, height) = image.dimensions();
            let image_data = image.into_raw().clone();

            vulkano::image::immutable::ImmutableImage::from_iter(
                image_data.iter().cloned(),
                vulkano::image::Dimensions::Dim2d { width: width, height: height },
                vulkano::format::R8G8B8A8Srgb,
                Some(queue.family()),
                queue.clone()).expect("failed to create immutable image")
        };
```
and then (after the set creation) storing the texture in a struct to keep it alive in my renderer?
I also tried to generate the descriptor_sets new per frame from the stored texture, the error still appears.

**Comment by tomaka** [comment]
> Sorry to come back, but the problem changed.

That's what I said above. The problem I fixed allows you to see what the actual error is.

> do I have to do something with the texture I pass to the descriptor set, besides creating it with

No, it is a buffer that you use without initializing it.

**Comment by SiebenCorgie** [comment]
Hmm, that makes no sense, because the image get initialised right before the set creation and the other buffer has to be initialised, otherwise the function for the texture and the two descriptor set won't fire.
However, I managed to create the same error on the triangle example when trying to add a texture to the triangle, you can see the code [here](https://gist.github.com/SiebenCorgie/36b9d519bb0f8efb3772f22c6ebdfa3c).

I basically just added the image loading + sampler + descriptor set and changed the shader to use the texture as colour in the fragment shader.

**Comment by tomaka** [comment]
Oh I see. The image is initialized only after `tex_future_albedo` future. You can either drop it to block the thread until this happens, or use that future as the base for follow-up operations.

For example if you replace:
```rust
let mut previous_frame_end = Box::new(now(device.clone())) as Box<GpuFuture>;
```
With:
```rust
let mut previous_frame_end = Box::new(tex_future_albedo) as Box<GpuFuture>;
```

Then it should work as well.

**Comment by SiebenCorgie** [comment]
Ah, that worked!
Many thanks for the help and your patients with me.
