### ISSUE TITLE
empty CpuBufferPool chunk (regression)

### ISSUE THREAD

**Issue by rukai** [vulkano-rs/vulkano#758]
I missed an issue with CpuBufferPoolChunk that occurs only when the first chunk is NOT empty, which I didnt test. (sorry)
This occurs on my windows install on the latest commit, and doesnt occur on the previous commit.

It panics with both:
```
thread 'main' panicked at 'assertion failed: chunk.num_gpu_accesses >= 1', /home/rubic/Projects/RustExamples/vulkano/vulkano/src/buffer/cpu_pool.rs:567:8
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /checkout/src/libcore/result.rs:906:4
```
Branch with example demonstrating the issue:https://github.com/rukai/vulkano/commit/f355ea2d3d88c1fadba40ecae0ea7a7159c2b360
Full output log: [out.txt](https://github.com/vulkano-rs/vulkano/files/1242174/out.txt)

**Comment by rukai** [comment]
@tomaka What was your reasoning for allowing empty buffers here? https://github.com/vulkano-rs/vulkano/pull/524
