### ISSUE TITLE
The triangle example panicked on Kubuntu 17.04 laptop with Intel HD Graphics

### ISSUE THREAD

**Issue by XX** [vulkano-rs/vulkano#762]
When I run the triangle example, I get this error:
```
Using device: Intel(R) HD Graphics 5500 (Broadwell GT2) (type: IntegratedGpu)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
`RUST_BACKTRACE` output is:
```
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:49
  10: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:21
  11: vulkano::descriptor::pipeline_layout::limits_check::check_desc_against_limits
             at /home/xx/rust_projects/vulkano/vulkano/src/descriptor/pipeline_layout/limits_check.rs:38
  12: vulkano::descriptor::pipeline_layout::traits::PipelineLayoutDesc::check_against_limits
             at /home/xx/rust_projects/vulkano/vulkano/src/descriptor/pipeline_layout/traits.rs:108
  13: <vulkano::descriptor::pipeline_layout::sys::PipelineLayout<L>>::new
             at /home/xx/rust_projects/vulkano/vulkano/src/descriptor/pipeline_layout/sys.rs:56
  14: vulkano::descriptor::pipeline_layout::traits::PipelineLayoutDesc::build
             at /home/xx/rust_projects/vulkano/vulkano/src/descriptor/pipeline_layout/traits.rs:118
  15: <vulkano::pipeline::graphics_pipeline::GraphicsPipeline<Vdef, (), Rp>>::with_tessellation_and_geometry
             at /home/xx/rust_projects/vulkano/vulkano/src/pipeline/graphics_pipeline/mod.rs:494
  16: <vulkano::pipeline::graphics_pipeline::builder::GraphicsPipelineBuilder<Vdef, Vs, Tcs, Tes, Gs, Fs, Rp>>::build
             at /home/xx/rust_projects/vulkano/vulkano/src/pipeline/graphics_pipeline/builder.rs:135
  17: triangle::main
             at src/bin/triangle.rs:282
  18: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  19: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  20: main
  21: __libc_start_main
  22: _start
```
However, the teapot example works fine.

**Comment by tomaka** [comment]
Oh that also explains #760

**Comment by tomaka** [comment]
For the record, basically the root bug is that vulkano-shaders would generate wrong code, and that's what #764 fixes. #757 only revealed the fact that there was a bug.
But since the output of vulkano-shaders was copy-pasted when the runtime shader example was written, the same bug also manifested as #760.

**Comment by XX** [comment]
@tomaka Thanks for the explanation!
