### ISSUE TITLE
Validation error with copy_buffer_to_image_dimensions

### ISSUE THREAD

**Issue by Kurble** [vulkano-rs/vulkano#902]
I have a texture atlas that is dynamically updated.
To do this, I have a StorageImage that I update by using copy_buffer_to_image_dimensions when there is some new data. 

`    let buffer = CpuAccessibleBuffer::from_iter(cmd.device().clone(), BufferUsage{
        transfer_source: true,
        .. BufferUsage::none()
    }, data.iter().cloned()).unwrap();

   cmd.copy_buffer_to_image_dimensions(
        buffer, 
        texture, 
        [offset[0], offset[1], 0], 
        [size[0], size[1], 1], 
        0, 
        1, 
        0
    ).unwrap()`

Later in the same command buffer, I use the same texture to do some draw commands, which succeeds. But the next time acquire is called on my swapchain I get the following panic: `thread 'main' panicked at 'unexpected error: ValidationFailed', C:\...\vulkano\src\swapchain\swapchain.rs:946:17`
If I remove the copy_buffer_to_image_dimensions command everything is fine.

Am I missing some synchronisation gotcha or is this is a bug?

**Comment by Kurble** [comment]
Now with the actual validation issue:
```
DS(ERROR): object: 0x280da90e8e0 type: 5 location: 12390 msgCode: 1952: vkAcquireNextImageKHR: Semaphore must not be currently signaled or in a wait state. For more information refer to Vulkan Spec Section '30.6. WSI Swapchain' which states 'If semaphore is not VK_NULL_HANDLE it must be unsignaled' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#vkAcquireNextImageKHR)
DS(ERROR): object: 0x280da9e38c0 type: 27 location: 12416 msgCode: 102: vkAcquireNextImageKHR: Application has already acquired the maximum number of images (0x1)
thread 'main' panicked at 'unexpected error: ValidationFailed', C:\Users\re-lion\.cargo\git\checkouts\vulkano-62e01abeda68e9d8\cfea566\vulkano\src\swapchain\swapchain.rs:946:17```
