### ISSUE TITLE
Triangle example crashes with DeviceLost when using version 0.7.2

### ISSUE THREAD

**Issue by andrewhickman** [vulkano-rs/vulkano#932]
When I run the triangle example from the repository directly it works fine. However when I try it in my own code using version 0.7.2 I get a crash on resizing the window. The only change I made was to replace line 108 with

```
let window = winit::WindowBuilder::new().build_vk_surface(&events_loop, instance.clone()).unwrap();
let surface = window.surface().clone()
```
Backtrace
```
Using device: GeForce GTX 750 Ti (type: DiscreteGpu)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DeviceLost', src\libcore\result.rs:916:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:56
   2: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:381
   3: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   5: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   7: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   8: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   9: core::result::unwrap_failed<vulkano::sync::future::FlushError>
             at C:\projects\rust\src\libcore\macros.rs:23
  10: core::result::Result<(), vulkano::sync::future::FlushError>::unwrap<(),vulkano::sync::future::FlushError>
             at C:\projects\rust\src\libcore\result.rs:782
  11: vulkano::command_buffer::traits::{{impl}}::drop<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture>,vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>
             at C:\Users\andre\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.7.2\src\command_buffer\traits.rs:330
  12: core::ptr::drop_in_place<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>>
             at C:\projects\rust\src\libcore\ptr.rs:59
  13: core::ptr::drop_in_place<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>>>
             at C:\projects\rust\src\libcore\ptr.rs:59
  14: vulkano::sync::future::fence_signal::FenceSignalFuture<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>>>::flush_impl<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>>>
             at C:\Users\andre\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.7.2\src\sync\future\fence_signal.rs:296
  15: vulkano::sync::future::fence_signal::{{impl}}::drop<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>>>
             at C:\Users\andre\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.7.2\src\sync\future\fence_signal.rs:431
  16: core::ptr::drop_in_place<vulkano::sync::future::fence_signal::FenceSignalFuture<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>>>>
             at C:\projects\rust\src\libcore\ptr.rs:59
  17: vulkano::sync::future::GpuFuture::then_signal_fence_and_flush<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>>>
             at C:\Users\andre\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.7.2\src\sync\future\mod.rs:230
  18: triangle::main
             at .\src\bin\triangle.rs:439
  19: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  20: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:476
  21: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:101
  22: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:50
  23: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  24: main
  25: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:259
  26: BaseThreadInitThunk
error: process didn't exit successfully: `C:\Users\andre\Documents\rust\vulkano\target\debug\triangle.exe` (exit code: 101)
```
This is with the change from #919.

**Comment by rukai** [comment]
That would make sense.
0.7.2 doesnt have this commit https://github.com/vulkano-rs/vulkano/commit/057507f7c2fd553ac7c80dff03c4a18f36f888f3 which makes resizing not explode.

**Comment by andrewhickman** [comment]
With the release of 0.8.0 this issue I think this issue can be closed
